version: '3.8'

services:
  sql_analysis:
    container_name: sql_analysis
    restart: "always"
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000

    # volumes:
    #   - "./:/app"
    #   - "./data/:/app/data"
    #   - "./logs/:/app/logs"

    ports:
      - "8000:8000"

    environment:
      - PYTHONPATH=${PYTHONPATH:-./app}
      - DB=${DB:-postgresql}
      - NAMEDB=${NAMEDB:-imdb_tv6k}
      - USERDB=${USERDB:-user}
      - PASSWORDDB=${PASSWORDDB:-Mj7Q17R6TY617bYkMa8mah8ZWvnB0LOw}
      - NAME_SERVICEDB=${NAME_SERVICEDB:-dpg-d22hvlumcj7s738ilm00-a.oregon-postgres.render.com}
      - PORT=${PORT_DB:-5432}